// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: me/header.proto

package me

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Header is the one message every schema version shares: field 1 of every envelope, in every
// version, is its schema version. A consumer decodes Header alone from any body to pick the
// matching decoder before it decodes anything else. Never add fields here.
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_me_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_me_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_me_header_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_me_header_proto protoreflect.FileDescriptor

const file_me_header_proto_rawDesc = "" +
	"\n" +
	"\x0fme/header.proto\x12\x02me\"\"\n" +
	"\x06Header\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversionb\x06proto3"

var (
	file_me_header_proto_rawDescOnce sync.Once
	file_me_header_proto_rawDescData []byte
)

func file_me_header_proto_rawDescGZIP() []byte {
	file_me_header_proto_rawDescOnce.Do(func() {
		file_me_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_me_header_proto_rawDesc), len(file_me_header_proto_rawDesc)))
	})
	return file_me_header_proto_rawDescData
}

var file_me_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_me_header_proto_goTypes = []any{
	(*Header)(nil), // 0: me.Header
}
var file_me_header_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_me_header_proto_init() }
func file_me_header_proto_init() {
	if File_me_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_me_header_proto_rawDesc), len(file_me_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_me_header_proto_goTypes,
		DependencyIndexes: file_me_header_proto_depIdxs,
		MessageInfos:      file_me_header_proto_msgTypes,
	}.Build()
	File_me_header_proto = out.File
	file_me_header_proto_goTypes = nil
	file_me_header_proto_depIdxs = nil
}
