// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: me/v1/commands.proto

package mev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenOrder struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         []byte                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId   string                 `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	MarketId        int32                  `protobuf:"varint,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId          []byte                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Side            OrderSide              `protobuf:"varint,5,opt,name=side,proto3,enum=me.v1.OrderSide" json:"side,omitempty"`
	Type            OrderType              `protobuf:"varint,6,opt,name=type,proto3,enum=me.v1.OrderType" json:"type,omitempty"`
	TimeInForce     TimeInForce            `protobuf:"varint,7,opt,name=time_in_force,json=timeInForce,proto3,enum=me.v1.TimeInForce" json:"time_in_force,omitempty"`
	Price           uint64                 `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	Quantity        uint64                 `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	QuoteQty        *uint64                `protobuf:"varint,10,opt,name=quote_qty,json=quoteQty,proto3,oneof" json:"quote_qty,omitempty"`
	ExpiresAt       *int64                 `protobuf:"varint,11,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	PostOnly        bool                   `protobuf:"varint,12,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	TakeProfitPrice *uint64                `protobuf:"varint,13,opt,name=take_profit_price,json=takeProfitPrice,proto3,oneof" json:"take_profit_price,omitempty"`
	StopLossPrice   *uint64                `protobuf:"varint,14,opt,name=stop_loss_price,json=stopLossPrice,proto3,oneof" json:"stop_loss_price,omitempty"`
	ParentOrderId   []byte                 `protobuf:"bytes,15,opt,name=parent_order_id,json=parentOrderId,proto3,oneof" json:"parent_order_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OpenOrder) Reset() {
	*x = OpenOrder{}
	mi := &file_me_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrder) ProtoMessage() {}

func (x *OpenOrder) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrder.ProtoReflect.Descriptor instead.
func (*OpenOrder) Descriptor() ([]byte, []int) {
	return file_me_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *OpenOrder) GetOrderId() []byte {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OpenOrder) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *OpenOrder) GetMarketId() int32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *OpenOrder) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *OpenOrder) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *OpenOrder) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *OpenOrder) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *OpenOrder) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OpenOrder) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OpenOrder) GetQuoteQty() uint64 {
	if x != nil && x.QuoteQty != nil {
		return *x.QuoteQty
	}
	return 0
}

func (x *OpenOrder) GetExpiresAt() int64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *OpenOrder) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *OpenOrder) GetTakeProfitPrice() uint64 {
	if x != nil && x.TakeProfitPrice != nil {
		return *x.TakeProfitPrice
	}
	return 0
}

func (x *OpenOrder) GetStopLossPrice() uint64 {
	if x != nil && x.StopLossPrice != nil {
		return *x.StopLossPrice
	}
	return 0
}

func (x *OpenOrder) GetParentOrderId() []byte {
	if x != nil {
		return x.ParentOrderId
	}
	return nil
}

type CancelOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       []byte                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MarketRef     string                 `protobuf:"bytes,2,opt,name=market_ref,json=marketRef,proto3" json:"market_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrder) Reset() {
	*x = CancelOrder{}
	mi := &file_me_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrder) ProtoMessage() {}

func (x *CancelOrder) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrder.ProtoReflect.Descriptor instead.
func (*CancelOrder) Descriptor() ([]byte, []int) {
	return file_me_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOrder) GetOrderId() []byte {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *CancelOrder) GetMarketRef() string {
	if x != nil {
		return x.MarketRef
	}
	return ""
}

type OrderCommand struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*OrderCommand_Open
	//	*OrderCommand_Cancel
	Command       isOrderCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCommand) Reset() {
	*x = OrderCommand{}
	mi := &file_me_v1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommand) ProtoMessage() {}

func (x *OrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommand.ProtoReflect.Descriptor instead.
func (*OrderCommand) Descriptor() ([]byte, []int) {
	return file_me_v1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCommand) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OrderCommand) GetCommand() isOrderCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *OrderCommand) GetOpen() *OpenOrder {
	if x != nil {
		if x, ok := x.Command.(*OrderCommand_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *OrderCommand) GetCancel() *CancelOrder {
	if x != nil {
		if x, ok := x.Command.(*OrderCommand_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isOrderCommand_Command interface {
	isOrderCommand_Command()
}

type OrderCommand_Open struct {
	Open *OpenOrder `protobuf:"bytes,10,opt,name=open,proto3,oneof"`
}

type OrderCommand_Cancel struct {
	Cancel *CancelOrder `protobuf:"bytes,11,opt,name=cancel,proto3,oneof"`
}

func (*OrderCommand_Open) isOrderCommand_Command() {}

func (*OrderCommand_Cancel) isOrderCommand_Command() {}

var File_me_v1_commands_proto protoreflect.FileDescriptor

const file_me_v1_commands_proto_rawDesc = "" +
	"\n" +
	"\x14me/v1/commands.proto\x12\x05me.v1\x1a\x11me/v1/types.proto\"\x83\x05\n" +
	"\tOpenOrder\x12\x19\n" +
	"\border_id\x18\x01 \x01(\fR\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x02 \x01(\tR\rclientOrderId\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\x05R\bmarketId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\fR\x06userId\x12$\n" +
	"\x04side\x18\x05 \x01(\x0e2\x10.me.v1.OrderSideR\x04side\x12$\n" +
	"\x04type\x18\x06 \x01(\x0e2\x10.me.v1.OrderTypeR\x04type\x126\n" +
	"\rtime_in_force\x18\a \x01(\x0e2\x12.me.v1.TimeInForceR\vtimeInForce\x12\x14\n" +
	"\x05price\x18\b \x01(\x04R\x05price\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x04R\bquantity\x12 \n" +
	"\tquote_qty\x18\n" +
	" \x01(\x04H\x00R\bquoteQty\x88\x01\x01\x12\"\n" +
	"\n" +
	"expires_at\x18\v \x01(\x03H\x01R\texpiresAt\x88\x01\x01\x12\x1b\n" +
	"\tpost_only\x18\f \x01(\bR\bpostOnly\x12/\n" +
	"\x11take_profit_price\x18\r \x01(\x04H\x02R\x0ftakeProfitPrice\x88\x01\x01\x12+\n" +
	"\x0fstop_loss_price\x18\x0e \x01(\x04H\x03R\rstopLossPrice\x88\x01\x01\x12+\n" +
	"\x0fparent_order_id\x18\x0f \x01(\fH\x04R\rparentOrderId\x88\x01\x01B\f\n" +
	"\n" +
	"_quote_qtyB\r\n" +
	"\v_expires_atB\x14\n" +
	"\x12_take_profit_priceB\x12\n" +
	"\x10_stop_loss_priceB\x12\n" +
	"\x10_parent_order_id\"G\n" +
	"\vCancelOrder\x12\x19\n" +
	"\border_id\x18\x01 \x01(\fR\aorderId\x12\x1d\n" +
	"\n" +
	"market_ref\x18\x02 \x01(\tR\tmarketRef\"\x89\x01\n" +
	"\fOrderCommand\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12&\n" +
	"\x04open\x18\n" +
	" \x01(\v2\x10.me.v1.OpenOrderH\x00R\x04open\x12,\n" +
	"\x06cancel\x18\v \x01(\v2\x12.me.v1.CancelOrderH\x00R\x06cancelB\t\n" +
	"\acommandb\x06proto3"

var (
	file_me_v1_commands_proto_rawDescOnce sync.Once
	file_me_v1_commands_proto_rawDescData []byte
)

func file_me_v1_commands_proto_rawDescGZIP() []byte {
	file_me_v1_commands_proto_rawDescOnce.Do(func() {
		file_me_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_me_v1_commands_proto_rawDesc), len(file_me_v1_commands_proto_rawDesc)))
	})
	return file_me_v1_commands_proto_rawDescData
}

var file_me_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_me_v1_commands_proto_goTypes = []any{
	(*OpenOrder)(nil),    // 0: me.v1.OpenOrder
	(*CancelOrder)(nil),  // 1: me.v1.CancelOrder
	(*OrderCommand)(nil), // 2: me.v1.OrderCommand
	(OrderSide)(0),       // 3: me.v1.OrderSide
	(OrderType)(0),       // 4: me.v1.OrderType
	(TimeInForce)(0),     // 5: me.v1.TimeInForce
}
var file_me_v1_commands_proto_depIdxs = []int32{
	3, // 0: me.v1.OpenOrder.side:type_name -> me.v1.OrderSide
	4, // 1: me.v1.OpenOrder.type:type_name -> me.v1.OrderType
	5, // 2: me.v1.OpenOrder.time_in_force:type_name -> me.v1.TimeInForce
	0, // 3: me.v1.OrderCommand.open:type_name -> me.v1.OpenOrder
	1, // 4: me.v1.OrderCommand.cancel:type_name -> me.v1.CancelOrder
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_me_v1_commands_proto_init() }
func file_me_v1_commands_proto_init() {
	if File_me_v1_commands_proto != nil {
		return
	}
	file_me_v1_types_proto_init()
	file_me_v1_commands_proto_msgTypes[0].OneofWrappers = []any{}
	file_me_v1_commands_proto_msgTypes[2].OneofWrappers = []any{
		(*OrderCommand_Open)(nil),
		(*OrderCommand_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_me_v1_commands_proto_rawDesc), len(file_me_v1_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_me_v1_commands_proto_goTypes,
		DependencyIndexes: file_me_v1_commands_proto_depIdxs,
		MessageInfos:      file_me_v1_commands_proto_msgTypes,
	}.Build()
	File_me_v1_commands_proto = out.File
	file_me_v1_commands_proto_goTypes = nil
	file_me_v1_commands_proto_depIdxs = nil
}
