// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: me/v1/events.proto

package mev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         uint64                 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint64                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TakerSide     OrderSide              `protobuf:"varint,3,opt,name=taker_side,json=takerSide,proto3,enum=me.v1.OrderSide" json:"taker_side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_me_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_me_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetTakerSide() OrderSide {
	if x != nil {
		return x.TakerSide
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          OrderSide              `protobuf:"varint,1,opt,name=side,proto3,enum=me.v1.OrderSide" json:"side,omitempty"`
	Price         uint64                 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_me_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_me_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *Book) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Book) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_me_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_me_v1_events_proto_rawDescGZIP(), []int{2}
}

type BookLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         uint64                 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      uint64                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookLevel) Reset() {
	*x = BookLevel{}
	mi := &file_me_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookLevel) ProtoMessage() {}

func (x *BookLevel) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookLevel.ProtoReflect.Descriptor instead.
func (*BookLevel) Descriptor() ([]byte, []int) {
	return file_me_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *BookLevel) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookLevel) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         string                 `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Market        string                 `protobuf:"bytes,3,opt,name=market,proto3" json:"market,omitempty"`
	Bids          []*BookLevel           `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*BookLevel           `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_me_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_me_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *Snapshot) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *Snapshot) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Snapshot) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Snapshot) GetBids() []*BookLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Snapshot) GetAsks() []*BookLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// status is a free string on purpose: the set grows with engine features and the wire must not
// gate it.
type OrderUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       []byte                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Filled        uint64                 `protobuf:"varint,3,opt,name=filled,proto3" json:"filled,omitempty"`
	Remaining     uint64                 `protobuf:"varint,4,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdate) Reset() {
	*x = OrderUpdate{}
	mi := &file_me_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdate) ProtoMessage() {}

func (x *OrderUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdate.ProtoReflect.Descriptor instead.
func (*OrderUpdate) Descriptor() ([]byte, []int) {
	return file_me_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *OrderUpdate) GetOrderId() []byte {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OrderUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderUpdate) GetFilled() uint64 {
	if x != nil {
		return x.Filled
	}
	return 0
}

func (x *OrderUpdate) GetRemaining() uint64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type Event struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Epoch   string                 `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Seq     uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Market  string                 `protobuf:"bytes,4,opt,name=market,proto3" json:"market,omitempty"`
	Ts      int64                  `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Trade
	//	*Event_Book
	//	*Event_Heartbeat
	//	*Event_Snapshot
	//	*Event_Order
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_me_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_me_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_me_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Event) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTrade() *Trade {
	if x != nil {
		if x, ok := x.Payload.(*Event_Trade); ok {
			return x.Trade
		}
	}
	return nil
}

func (x *Event) GetBook() *Book {
	if x != nil {
		if x, ok := x.Payload.(*Event_Book); ok {
			return x.Book
		}
	}
	return nil
}

func (x *Event) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Event_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Event) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Payload.(*Event_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Event) GetOrder() *OrderUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Event_Order); ok {
			return x.Order
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Trade struct {
	Trade *Trade `protobuf:"bytes,10,opt,name=trade,proto3,oneof"`
}

type Event_Book struct {
	Book *Book `protobuf:"bytes,11,opt,name=book,proto3,oneof"`
}

type Event_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

type Event_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,13,opt,name=snapshot,proto3,oneof"`
}

type Event_Order struct {
	Order *OrderUpdate `protobuf:"bytes,14,opt,name=order,proto3,oneof"`
}

func (*Event_Trade) isEvent_Payload() {}

func (*Event_Book) isEvent_Payload() {}

func (*Event_Heartbeat) isEvent_Payload() {}

func (*Event_Snapshot) isEvent_Payload() {}

func (*Event_Order) isEvent_Payload() {}

var File_me_v1_events_proto protoreflect.FileDescriptor

const file_me_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x12me/v1/events.proto\x12\x05me.v1\x1a\x11me/v1/types.proto\"j\n" +
	"\x05Trade\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x04R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x04R\bquantity\x12/\n" +
	"\n" +
	"taker_side\x18\x03 \x01(\x0e2\x10.me.v1.OrderSideR\ttakerSide\"^\n" +
	"\x04Book\x12$\n" +
	"\x04side\x18\x01 \x01(\x0e2\x10.me.v1.OrderSideR\x04side\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x04R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\"\v\n" +
	"\tHeartbeat\"=\n" +
	"\tBookLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x04R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x04R\bquantity\"\x96\x01\n" +
	"\bSnapshot\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\tR\x05epoch\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06market\x18\x03 \x01(\tR\x06market\x12$\n" +
	"\x04bids\x18\x04 \x03(\v2\x10.me.v1.BookLevelR\x04bids\x12$\n" +
	"\x04asks\x18\x05 \x03(\v2\x10.me.v1.BookLevelR\x04asks\"v\n" +
	"\vOrderUpdate\x12\x19\n" +
	"\border_id\x18\x01 \x01(\fR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06filled\x18\x03 \x01(\x04R\x06filled\x12\x1c\n" +
	"\tremaining\x18\x04 \x01(\x04R\tremaining\"\xd2\x02\n" +
	"\x05Event\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\tR\x05epoch\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06market\x18\x04 \x01(\tR\x06market\x12\x0e\n" +
	"\x02ts\x18\x05 \x01(\x03R\x02ts\x12$\n" +
	"\x05trade\x18\n" +
	" \x01(\v2\f.me.v1.TradeH\x00R\x05trade\x12!\n" +
	"\x04book\x18\v \x01(\v2\v.me.v1.BookH\x00R\x04book\x120\n" +
	"\theartbeat\x18\f \x01(\v2\x10.me.v1.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\bsnapshot\x18\r \x01(\v2\x0f.me.v1.SnapshotH\x00R\bsnapshot\x12*\n" +
	"\x05order\x18\x0e \x01(\v2\x12.me.v1.OrderUpdateH\x00R\x05orderB\t\n" +
	"\apayloadb\x06proto3"

var (
	file_me_v1_events_proto_rawDescOnce sync.Once
	file_me_v1_events_proto_rawDescData []byte
)

func file_me_v1_events_proto_rawDescGZIP() []byte {
	file_me_v1_events_proto_rawDescOnce.Do(func() {
		file_me_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_me_v1_events_proto_rawDesc), len(file_me_v1_events_proto_rawDesc)))
	})
	return file_me_v1_events_proto_rawDescData
}

var file_me_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_me_v1_events_proto_goTypes = []any{
	(*Trade)(nil),       // 0: me.v1.Trade
	(*Book)(nil),        // 1: me.v1.Book
	(*Heartbeat)(nil),   // 2: me.v1.Heartbeat
	(*BookLevel)(nil),   // 3: me.v1.BookLevel
	(*Snapshot)(nil),    // 4: me.v1.Snapshot
	(*OrderUpdate)(nil), // 5: me.v1.OrderUpdate
	(*Event)(nil),       // 6: me.v1.Event
	(OrderSide)(0),      // 7: me.v1.OrderSide
}
var file_me_v1_events_proto_depIdxs = []int32{
	7, // 0: me.v1.Trade.taker_side:type_name -> me.v1.OrderSide
	7, // 1: me.v1.Book.side:type_name -> me.v1.OrderSide
	3, // 2: me.v1.Snapshot.bids:type_name -> me.v1.BookLevel
	3, // 3: me.v1.Snapshot.asks:type_name -> me.v1.BookLevel
	0, // 4: me.v1.Event.trade:type_name -> me.v1.Trade
	1, // 5: me.v1.Event.book:type_name -> me.v1.Book
	2, // 6: me.v1.Event.heartbeat:type_name -> me.v1.Heartbeat
	4, // 7: me.v1.Event.snapshot:type_name -> me.v1.Snapshot
	5, // 8: me.v1.Event.order:type_name -> me.v1.OrderUpdate
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_me_v1_events_proto_init() }
func file_me_v1_events_proto_init() {
	if File_me_v1_events_proto != nil {
		return
	}
	file_me_v1_types_proto_init()
	file_me_v1_events_proto_msgTypes[6].OneofWrappers = []any{
		(*Event_Trade)(nil),
		(*Event_Book)(nil),
		(*Event_Heartbeat)(nil),
		(*Event_Snapshot)(nil),
		(*Event_Order)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_me_v1_events_proto_rawDesc), len(file_me_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_me_v1_events_proto_goTypes,
		DependencyIndexes: file_me_v1_events_proto_depIdxs,
		MessageInfos:      file_me_v1_events_proto_msgTypes,
	}.Build()
	File_me_v1_events_proto = out.File
	file_me_v1_events_proto_goTypes = nil
	file_me_v1_events_proto_depIdxs = nil
}
